CREATE TABLE IF NOT EXISTS FLIGHT (
    ID IDENTITY NOT NULL PRIMARY KEY,
    AIRLINE_NAME VARCHAR(100) NOT NULL,
    SUPPLIER VARCHAR(100) NOT NULL,
    FARE NUMERIC (38)  NOT NULL,
    DEPATURE VARCHAR(3) NOT NULL,
    DESTINATION VARCHAR(3) NOT NULL,
    DEPATURE_TIME   DATETIME2 (3)  NOT NULL,
    ARRIVAL_TIME   DATETIME2 (3)  NOT NULL,

    CONSTRAINT report_unique_constraint
    UNIQUE (AIRLINE_NAME, SUPPLIER, FARE, DEPATURE, DESTINATION, DEPATURE_TIME, ARRIVAL_TIME)
    );
INSERT INTO FLIGHT (AIRLINE_NAME, SUPPLIER, FARE, DEPATURE, DESTINATION, DEPATURE_TIME, ARRIVAL_TIME)
VALUES ('Alpha Airlines', 'Airline supplier 1', '2000', 'ATL','AMS', '2025-07-01T03:43:29.422Z', '2025-08-01T17:07:00.604Z');


CREATE TABLE IF NOT EXISTS SUPPLIER_FLIGHT (

    ID IDENTITY NOT NULL PRIMARY KEY,
    CARRIER_NAME VARCHAR(100) NOT NULL,
    BASE_PRICE NUMERIC (38)  NOT NULL,
    TAX NUMERIC (38)  NOT NULL,
    DEPATURE VARCHAR(3) NOT NULL,
    ARIVAL VARCHAR(3) NOT NULL,
    OUTBOUND_TIME   DATETIME2 (3)  NOT NULL,
    INBOUND_TIME   DATETIME2 (3)  NOT NULL
    );
INSERT INTO SUPPLIER_FLIGHT (CARRIER_NAME, BASE_PRICE, TAX, DEPATURE, ARIVAL, OUTBOUND_TIME, INBOUND_TIME)
VALUES ('Alpha supplier Airlines', '2000', '200', 'ATL','AMS', '2025-07-01T03:43:29.422Z', '2025-08-01T17:07:00.604Z');
INSERT INTO SUPPLIER_FLIGHT (CARRIER_NAME, BASE_PRICE, TAX, DEPATURE, ARIVAL, OUTBOUND_TIME, INBOUND_TIME)
VALUES ('Beta supplier Airlines', '2000', '200', 'ATL','AMS', '2025-07-01T03:43:29.422Z', '2025-08-01T17:07:00.604Z');
